name: "Chipmango-Ad - Publish to Maven Repository"
on:
  push:
    branches: [ master ]
jobs:
  changelog:
    runs-on: ubuntu-20.04
    steps:
      - name: "Check out repository code"
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.ACTION_TOKEN }}
      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

        # Builds the release artifacts of the library
      - name: Release build
        run: ./gradlew :chipmango-ad:assembleRelease

        # Generates other artifacts (javadocJar is optional)
      - name: Source jar
        run: ./gradlew androidSourcesJar

        # Runs upload, and then closes & releases the repository
      - name: Publish to MavenCentral
        run: ./gradlew publishReleasePublicationToSonatypeRepository --max-workers 1 closeAndReleaseSonatypeStagingRepository
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          SONATYPE_STAGING_PROFILE_ID: ${{ secrets.SONATYPE_STAGING_PROFILE_ID }}

